apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: test-complex-patch
spec:
  patches:
    test-complex-patch:
      targetObjectRef:
        apiVersion: v1
        kind: ServiceAccount
        name: test
        namespace: test-patch-operator
      patchTemplate: |
        metadata:
          annotations:
            {{ (index . 1).metadata.name }}: {{ (index . 2).metadata.name }}    
      patchType: application/strategic-merge-patch+json
      sourceObjectRefs:
      - apiVersion: v1
        kind: Namespace
        name: test-patch-operator
      - apiVersion: v1
        kind: ServiceAccount
        name: default
        namespace: test-patch-operator